language: node_js
node_js: node
deploy:
  provider: heroku
  api_key: agile-eyrie-53354
    secure: KpaGNHUTmA0p0u1d3hnb7vU4JNKG7JTyomGylalWqoHWiEMKo9aZg673LTQrAlUxFpbYfO55oswofIw9zWyf+VY7t155ZxNU2I6CqVngC4lfbc/QXkE3XzGoChlnlr4IyQmxDO1UgnbpgD0BqOQOGI49TTJ5wC3oFsEHBZrYQl6RCEh0Ma353lliwKDId+caWTFo+y/5hLqsMKVBrT4xWtJrLBAHkiPLWW7OJZHzFJv91uCeH2HVHvDlDnOkWwMtd2V/asGam4TnF0R45LKPc41Hbmo+ykZ5ZizNc2bjHZ51KS1Y+PQsFPbkzVCfmNfxMfMrYJl2ed7SGLWnLhhu+53cnDpvlNkVqwHBQOJWwKEnqP70ROq7+wQWV1tdCZLvxTLmm1EzqEZXseH/pQIS+lLIM6WSXcOf5wHP6cNCaRzXaHW6laDNRtE2sw4Aj6x5iLCqpB7FM0YW/8sVkJNjubqeNaJWkfb2VKrWTWUIp4yCr6zs8hLxt0Pd8oC4Ci1MTGW/0JJEMaHCU88DdZfdQ7A/9/l7wAcPkm0S2NiRKQVdNvxtY3+GcsfpGkukQRS1guhh4cnHszRafl6MuiGrRRPDVzYOf2t8Nv1CrXy7b8ArX8AtumkqwlDFQ4tDKUUhD2r0pB6BNQ8EELGM8LKR5M2HHIjE/LyKlu7T5YmQnVw=
  app: doga-forum
  on:
    repo: maxbfrecka/doga-forum
